server:
  port: 8888 #应用端口


spring:
  profiles:
    active: dev #环境配置
  application:
    name: academy #服务的名字

  datasource: #mysql相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academy?serverTimezone=UTC
    username: root
    password: root
  jackson: #返回json的格式
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志